### ISSUE TITLE
V2 Release checklist

### ISSUE THREAD

**Issue by Petethegoat** [NullCascade/morrowind-mods#21]
- [ ] attribute buffs may be displayed incorrectly immediately after chargen, before saving/loading
- [x] containers such as plants still show capacity even if their capacity is 0
- [x] roll in mort's minimap thing
- [x] check credit list after rolling in mort's minimap thing
- [ ] ongoing journal/dialogue weirdness? see below.
- [ ] new mcm with merlord's stuff?
- [ ] inventory searchbar doesn't seem to toggle on/off cleanly, probably some obvious error
- [x] spell list deletion bug- issue #23 
- [ ] menu pointer error when mashing buttons to search and opening/closing containers (@jhaakma)
- [ ] menu pointer error when starting a new game, after loading a game. #26 

journal weirdness:
![image](https://user-images.githubusercontent.com/734762/52597806-8b70db00-2e19-11e9-88ad-544d6a91d846.png)
